[program:reviewme-reverb]
command      = php /var/www/html/artisan reverb:start --debug
directory    = /var/www/html
user         = www-data
priority     = 45
autostart    = true
autorestart  = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
